### ISSUE TITLE
Shouldn't init git if already in a git repo

### ISSUE THREAD

**Issue by Akryum** [Akryum/nodepack#9]
Creating a Nodepack project inside a git repository (for example a mono-repo) is still initializing a new repository in the nodepack project folder.

**Comment by alemagio** [comment]
Hi, i've seen this project and it looks cool
I would like to try and solve this if it is ok

**Comment by Akryum** [comment]
Hi, thanks! You should try to reproduce it first, it may have been resolved already. 😸

**Comment by alemagio** [comment]
I think this is already resolved, i checked following this steps:
1- creating a new directory with .git directory in it
2- inside this directory used "nodepack create myproject"
3- in the newly created project directory there was no .git directory
gitignore file was created but i believe this is correct

**Comment by Akryum** [comment]
Awesome!
